name: Daily Data Update (Adelaide Time Midnight)
on:
  schedule:
    # Runs at 12 AM Adelaide time year-round (UTC+9:30/+10:30)
    - cron: '30 14 * * *'  # 2:30 PM UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pip-tools
          pip install lxml[html_clean]  # Critical fix for newspaper3k
          pip-compile --generate-hashes --output-file requirements.lock
          pip install -r requirements.lock
          python -m nltk.downloader punkt  # NLTK data

      - name: Run data pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Data update: $(date -d '+9:30' +'%Y-%m-%d %H:%M ACST')"
          git push
